// Copyright (c) 2026 Fleming Patel. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file axiom_dialect.hpp
 * @brief Axiom MLIR Dialect Definition for Strongly-Typed Pipeline IR
 * @author Fleming Patel
 *
 * OVERVIEW:
 * =========
 * This header defines Axiom's optional MLIR authoring dialect. ODS verifies
 * operation and attribute types; the frontend lowers the closed string-valued
 * vocabulary into the typed protobuf contract before semantic admission. The
 * dialect enables:
 *
 * - **Type Checking**: Parse-time verification of required string attributes
 * - **Canonicalization**: Deterministic ordering of pipeline elements
 * - **Verification**: Semantic validation at the MLIR level
 *
 * DIALECT ARCHITECTURE:
 * ====================
 * The Axiom dialect (MLIR namespace `axiom`, operation prefix `axiom.core.`)
 * defines the following operations:
 *
 * - `axiom.core.stage`: Declares a pipeline processing stage
 *   - Required string attributes: `stage_id`, `kind`, `execution_mode`
 *   - Kind-specific string attributes: `interface`, `module_id`, `module_path`, `context_selection`
 *
 * - `axiom.core.edge`: Declares a data flow connection between stages
 *   - Required string attributes: `from`, `to`, `mode`
 *
 * ODS/TABLEGEN INTEGRATION:
 * ========================
 * Operation definitions are specified in AxiomOps.td and processed by MLIR
 * TableGen to generate C++ declarations and definitions. This approach ensures:
 * - Consistent operation interfaces
 * - Automatic verification infrastructure
 * - Integration with MLIR tooling (mlir-opt, etc.)
 *
 * BUILD REQUIREMENTS:
 * ==================
 * This header requires MLIR support enabled at build time:
 *   cmake -DKINETUM_ENABLE_MLIR=ON -DKINETUM_ENABLE_MLIR_DIALECT=ON ..
 *
 * @note The dialect is optional; pipelines can also be authored in .pbtxt format.
 * @warning Including this header without KINETUM_ENABLE_MLIR=ON triggers a compile error.
 *
 * @see axiom_ops.hpp for operation declarations
 * @see axiom_passes.hpp for canonicalization and verification passes
 * @see axiom_mlir_frontend.hpp for high-level MLIR loading API
 */

#if !KINETUM_ENABLE_MLIR
#error "axiom_dialect.hpp included but KINETUM_ENABLE_MLIR=0"
#endif

#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

/**
 * @namespace kinetum::axiom::axiom_mlir
 * @brief MLIR dialect implementation for Axiom pipeline IR.
 *
 * This namespace contains all MLIR-specific types and functions for the
 * Axiom dialect, including:
 * - AxiomDialect class (registered with MLIR context)
 * - Operation classes (StageOp, EdgeOp)
 * - Pass factory functions
 *
 * @note Keep distinct from kinetum::axiom (protobuf-based IR) to avoid conflicts.
 */
namespace kinetum::axiom::axiom_mlir
{
}  // namespace kinetum::axiom::axiom_mlir

// Dialect declarations generated by TableGen.
// Requires: -DKINETUM_ENABLE_MLIR=ON -DKINETUM_ENABLE_MLIR_DIALECT=ON
#define GET_DIALECT_DECLS
#include "AxiomDialect.h.inc"
