// Copyright (c) 2026 Fleming Patel. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file axiom_ops.hpp
 * @brief Axiom MLIR Operation Declarations Generated via ODS/TableGen
 * @author Fleming Patel
 *
 * OVERVIEW:
 * =========
 * This header provides C++ declarations for Axiom MLIR operations, generated
 * from TableGen (.td) definitions via the MLIR ODS (Operation Definition Specification)
 * framework. These operations form the core IR for representing Axiom pipelines
 * in the MLIR ecosystem.
 *
 * OPERATION CATALOG:
 * =================
 * The following operations are defined by the Axiom dialect:
 *
 * **axiom.core.stage** (CoreStageOp):
 *   Represents a processing stage in the pipeline.
 *   @code
 *   "axiom.core.stage"() {stage_id = "rx", kind = "RX",
 *                          execution_mode = "PASSIVE", interface = "wan0"} : () -> ()
 *   "axiom.core.stage"() {stage_id = "filter", kind = "MODULE",
 *                          execution_mode = "PASSIVE", module_id = "kinetum.acl",
 *                          context_selection = "SAME_LANE"} : () -> ()
 *   @endcode
 *
 *   Attributes:
 *   - stage_id (StringAttr): Unique identifier for the stage
 *   - kind (StringAttr): Stage type (RX, TX, PARSE_IPV4, MODULE)
 *   - execution_mode (StringAttr): Explicit PASSIVE mode
 *   - interface (StringAttr): Required only for RX and TX
 *   - module_id/module_path (StringAttr): Module identity and optional source path
 *   - context_selection (StringAttr): Required SAME_LANE or MODULE for module stages
 *
 * **axiom.core.edge** (CoreEdgeOp):
 *   Represents a data flow edge connecting two stages.
 *   @code
 *   "axiom.core.edge"() {from = "rx", to = "parse", mode = "PUSH"} : () -> ()
 *   "axiom.core.edge"() {from = "parse", to = "acl", mode = "PUSH"} : () -> ()
 *   @endcode
 *
 *   Attributes:
 *   - from (StringAttr): Source stage ID
 *   - to (StringAttr): Destination stage ID
 *   - mode (StringAttr): Explicit PUSH mode
 *
 * ODS/TABLEGEN WORKFLOW:
 * =====================
 * 1. Operations defined in AxiomOps.td (TableGen DSL)
 * 2. mlir-tblgen generates AxiomOps.h.inc (declarations)
 * 3. mlir-tblgen generates AxiomOps.cpp.inc (definitions)
 * 4. This header includes the generated declarations
 *
 * USAGE:
 * ======
 * @code
 * #include "src/axiom/mlir/axiom_ops.hpp"
 *
 * // Access operation classes (generated from AxiomOps.td)
 * using kinetum::axiom::axiom_mlir::CoreStageOp;
 * using kinetum::axiom::axiom_mlir::CoreEdgeOp;
 *
 * // Create operations via OpBuilder
 * OpBuilder builder(context);
 * auto stage = builder.create<CoreStageOp>(loc, ...);
 * @endcode
 *
 * BUILD REQUIREMENTS:
 * ==================
 * Requires MLIR support enabled at build time:
 *   cmake -DKINETUM_ENABLE_MLIR=ON -DKINETUM_ENABLE_MLIR_DIALECT=ON ..
 *
 * @note Operations are registered with the dialect automatically.
 * @warning Including this header without KINETUM_ENABLE_MLIR=ON triggers a compile error.
 *
 * @see axiom_dialect.hpp for dialect definition
 * @see axiom_passes.hpp for operation-level passes
 */

#if !KINETUM_ENABLE_MLIR
#error "axiom_ops.hpp included but KINETUM_ENABLE_MLIR=0"
#endif

#include "src/axiom/mlir/axiom_dialect.hpp"

// Op declarations generated by TableGen.
// GET_OP_DECLS expands to class declarations for all operations
// defined in AxiomOps.td, including builders, verifiers, and accessors.
#define GET_OP_DECLS
#include "AxiomOps.h.inc"
