# Build the private wheel from the owning build's validation install component.
cmake_minimum_required(VERSION 3.28)
if(NOT DEFINED build_root OR NOT IS_ABSOLUTE "${build_root}" OR
   NOT DEFINED python OR NOT IS_ABSOLUTE "${python}")
  message(FATAL_ERROR "Validation-kit staging requires its owning build and Python interpreter")
endif()
set(kit_parent "${build_root}/validation/kit")
file(MAKE_DIRECTORY "${kit_parent}")
file(LOCK "${kit_parent}" DIRECTORY GUARD PROCESS TIMEOUT 0 RESULT_VARIABLE lock_result)
if(NOT lock_result STREQUAL "0")
  message(FATAL_ERROR "Validation-kit staging is already in use: ${lock_result}")
endif()
set(stage "${kit_parent}/stage")
set(candidate "${kit_parent}/candidate")
file(REMOVE_RECURSE "${stage}" "${candidate}")
file(MAKE_DIRECTORY "${stage}" "${candidate}")
set(environment /usr/bin/env -i PATH=/usr/sbin:/usr/bin:/sbin:/bin LC_ALL=C "TMPDIR=${stage}")
execute_process(
  COMMAND ${environment} "${CMAKE_COMMAND}" --install "${build_root}" --config Release
    --prefix "${stage}" --component KinetumValidationKit
  RESULT_VARIABLE result)
if(result STREQUAL "0")
  execute_process(
    COMMAND ${environment} "${python}" -I -B -m build --no-isolation --wheel --outdir "${candidate}"
    WORKING_DIRECTORY "${stage}/validation" RESULT_VARIABLE result TIMEOUT 300)
endif()
file(REMOVE_RECURSE "${stage}")
if(NOT result STREQUAL "0")
  file(REMOVE_RECURSE "${candidate}")
  message(FATAL_ERROR "Validation-kit staging failed: ${result}")
endif()
file(GLOB wheels "${candidate}/kinetum_validation-*.whl")
list(LENGTH wheels wheel_count)
if(NOT wheel_count EQUAL 1)
  file(REMOVE_RECURSE "${candidate}")
  message(FATAL_ERROR "Validation packaging did not produce exactly one wheel")
endif()
list(GET wheels 0 wheel)
get_filename_component(wheel_name "${wheel}" NAME)
set(output "${build_root}/${wheel_name}")
message(STATUS "Publishing private validation transport: ${output}")
file(RENAME "${wheel}" "${output}" RESULT result)
file(REMOVE_RECURSE "${candidate}")
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "Validation-kit publication failed: ${result}")
endif()
