// Copyright (c) 2026 Fleming Patel. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file provider_build_identity.hpp
 * @brief Typed access to the generated exact provider ABI identity.
 * @author Fleming Patel
 *
 * CMake derives the identity from the sole C ABI header and every pure provider
 * contract schema. This wrapper exposes the same generated bytes to C++ runtime
 * admission without adding another value source.
 */

#include <cstdint>
#include <string_view>

#include "gen/kinetum/provider/provider_build_identity.h"
#include "src/common/sha256_digest.hpp"
#include "src/provider/provider_component_abi.h"

namespace kinetum::provider
{

inline constexpr common::sha256_digest PROVIDER_ABI_IDENTITY =
	KINETUM_PROVIDER_ABI_IDENTITY_INITIALIZER;  ///< Exact generated ABI digest.
inline constexpr uint16_t PROVIDER_PRODUCT_VERSION_MAJOR =
	KINETUM_PROVIDER_PRODUCT_VERSION_MAJOR;	 ///< Exact product major version.
inline constexpr uint16_t PROVIDER_PRODUCT_VERSION_MINOR =
	KINETUM_PROVIDER_PRODUCT_VERSION_MINOR;	 ///< Exact product minor version.
inline constexpr uint16_t PROVIDER_PRODUCT_VERSION_PATCH =
	KINETUM_PROVIDER_PRODUCT_VERSION_PATCH;	 ///< Exact product patch version.
inline constexpr std::string_view PROVIDER_ABI_IDENTITY_HEX =
	KINETUM_PROVIDER_ABI_IDENTITY_HEX;  ///< Lowercase hexadecimal ABI identity.

static_assert(PROVIDER_ABI_IDENTITY.size() == KINETUM_PROVIDER_ABI_IDENTITY_SIZE,
	      "generated provider ABI identity width disagrees with the C ABI");

}  // namespace kinetum::provider
