// Copyright (c) 2026 Fleming Patel. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#pragma once

/**
 * @file ratelimit.hpp
 * @brief Rate limiting algorithms.
 * @author Fleming Patel
 *
 * Contains:
 * - Token Bucket: Standard rate limiting with burst allowance
 * - Exact integer-rational accrual without floating-point
 *
 * Token Bucket Algorithm:
 * - Tokens accumulate at rate R (bytes/second)
 * - Bucket holds maximum B tokens (burst size)
 * - Each packet consumes tokens equal to its size
 * - If tokens >= packet_size: allow and consume
 * - If tokens < packet_size: drop (rate limited)
 *
 * The primitives are reusable SDK mechanisms. The built-in QoS module keeps a
 * separate context-local policer whose state layout is part of that module's
 * packet-path contract.
 */

#include <cstddef>
#include <cstdint>
#include <stdexcept>

#include <kinetum/algo/platform.hpp>

namespace kinetum::algo
{

// =============================================================================
// Exact Rate Numerator
// =============================================================================

/** @cond INTERNAL_IMPLEMENTATION */
namespace detail
{

/** One exact byte balance numerator is divided by this nanosecond scale. */
inline constexpr uint64_t RATE_DENOMINATOR = 1'000'000'000u;

/** Exact wide type for a full uint64 rate multiplied by a full uint64 interval. */
using rate_numerator = unsigned __int128;

/**
 * @brief Convert an integer byte quantity to the exact rate numerator domain.
 * @param bytes Whole byte quantity.
 * @return Exact @p bytes multiplied by `RATE_DENOMINATOR`.
 */
[[nodiscard]] KINETUM_ALWAYS_INLINE KINETUM_CONST constexpr rate_numerator byte_numerator(uint64_t bytes) noexcept
{
	return static_cast<rate_numerator>(bytes) * RATE_DENOMINATOR;
}

/**
 * @brief Derive exact accrued byte numerator from elapsed nanoseconds and rate.
 * @param elapsed_ns Exact monotonic elapsed nanoseconds.
 * @param rate_bytes_per_sec Exact whole-byte rate per second.
 * @return Exact product; two uint64 factors are representable in 128 bits.
 */
[[nodiscard]] KINETUM_ALWAYS_INLINE KINETUM_CONST constexpr rate_numerator
accrued_numerator(uint64_t elapsed_ns, uint64_t rate_bytes_per_sec) noexcept
{
	return static_cast<rate_numerator>(elapsed_ns) * rate_bytes_per_sec;
}

}  // namespace detail
/** @endcond */

// =============================================================================
// Token Bucket
// =============================================================================

/**
 * @brief Token bucket for rate limiting.
 *
 * Implements the standard token bucket algorithm with an exact rational byte
 * balance. The internal numerator carries every fractional byte generated by
 * an integer bytes-per-second rate at nanosecond timestamps.
 *
 * @par Thread Safety
 * One caller owns each bucket. Shared use requires external synchronization.
 *
 * @par Performance
 * Construction initializes fixed state. `allow()` performs fixed-width
 * arithmetic and allocates, locks, and reads no clock.
 */
class token_bucket {
    public:
	/**
	 * @brief Construct token bucket.
	 *
	 * @param rate_bytes_per_sec Token accumulation rate in bytes per second.
	 * @param burst_bytes Maximum whole-byte bucket capacity.
	 */
	constexpr token_bucket(uint64_t rate_bytes_per_sec, uint64_t burst_bytes) noexcept
		: rate_bytes_per_sec_(rate_bytes_per_sec)
		, burst_bytes_(burst_bytes)
		, token_numerator_(detail::byte_numerator(burst_bytes))
		, last_ns_(0)
		, initialized_(false)
	{
	}

	/**
	 * @brief Check if packet should be allowed.
	 *
	 * Updates token count based on elapsed time, then checks if
	 * there are enough tokens for the packet.
	 *
	 * @param now_ns Explicit monotonic timestamp in nanoseconds.
	 * @param bytes Whole-byte cost.
	 * @return true if allowed and consumed; false for insufficient credit or
	 *         timestamp regression. Rejection preserves cost ownership.
	 */
	[[nodiscard]]
	KINETUM_ALWAYS_INLINE bool allow(uint64_t now_ns, std::size_t bytes) noexcept
	{
		if (KINETUM_UNLIKELY(!initialized_)) {
			last_ns_ = now_ns;
			initialized_ = true;
		} else if (KINETUM_UNLIKELY(now_ns < last_ns_)) {
			return false;
		} else if (now_ns > last_ns_) {
			const uint64_t elapsed_ns = now_ns - last_ns_;
			const detail::rate_numerator generated =
				detail::accrued_numerator(elapsed_ns, rate_bytes_per_sec_);
			const detail::rate_numerator capacity = detail::byte_numerator(burst_bytes_);
			const detail::rate_numerator available = capacity - token_numerator_;
			if (generated >= available) {
				token_numerator_ = capacity;
			} else {
				token_numerator_ += generated;
			}
			last_ns_ = now_ns;
		}

		static_assert(sizeof(std::size_t) <= sizeof(uint64_t));
		const detail::rate_numerator cost = detail::byte_numerator(static_cast<uint64_t>(bytes));
		if (token_numerator_ >= cost) {
			token_numerator_ -= cost;
			return true;
		}

		return false;  // Rate limited
	}

	/** @return Whole available bytes, excluding retained fractional credit. */
	[[nodiscard]] constexpr uint64_t tokens() const noexcept
	{
		return static_cast<uint64_t>(token_numerator_ / detail::RATE_DENOMINATOR);
	}

	/** @return Exact configured whole-byte capacity. */
	[[nodiscard]] constexpr uint64_t burst() const noexcept
	{
		return burst_bytes_;
	}

	/** @brief Reset to full capacity with an unbound timestamp baseline. */
	void reset() noexcept
	{
		token_numerator_ = detail::byte_numerator(burst_bytes_);
		last_ns_ = 0;
		initialized_ = false;
	}

	/**
	 * @brief Replace rate and burst without retroactive accrual.
	 *
	 * Existing whole-byte credit is retained up to the new capacity. Fractional
	 * credit from the old rate is discarded and the next accepted timestamp
	 * establishes a fresh baseline.
	 *
	 * @param rate_bytes_per_sec New exact whole-byte rate.
	 * @param burst_bytes New exact whole-byte capacity.
	 */
	void reconfigure(uint64_t rate_bytes_per_sec, uint64_t burst_bytes) noexcept
	{
		const uint64_t current_tokens = tokens();
		const uint64_t retained_bytes = current_tokens < burst_bytes ? current_tokens : burst_bytes;
		token_numerator_ = detail::byte_numerator(retained_bytes);
		rate_bytes_per_sec_ = rate_bytes_per_sec;
		burst_bytes_ = burst_bytes;
		last_ns_ = 0u;
		initialized_ = false;
	}

    private:
	uint64_t rate_bytes_per_sec_;		  ///< Exact configured whole-byte rate.
	uint64_t burst_bytes_;			  ///< Exact maximum whole-byte capacity.
	detail::rate_numerator token_numerator_;  ///< Exact balance over the shared denominator.
	uint64_t last_ns_;			  ///< Last accepted timestamp.
	bool initialized_;			  ///< Whether the timestamp baseline is bound, including zero.
};

// =============================================================================
// Leaky Bucket (Alternative Rate Limiter)
// =============================================================================

/**
 * @brief Leaky-bucket meter with a fixed drain rate and bounded burst capacity.
 *
 * Accepted bytes raise the level; elapsed time drains it at the configured
 * rate. Calls at the same timestamp can admit a burst up to available capacity.
 * The caller owns packet disposition; this meter does not queue or pace output.
 *
 * Algorithm:
 * - Bucket "leaks" at constant rate R
 * - Each accepted packet adds its byte cost to the level
 * - If bucket would overflow: reject without adding the packet's cost
 *
 * @par Thread Safety
 * One caller owns each bucket. Shared use requires external synchronization.
 */
class leaky_bucket {
    public:
	/**
	 * @brief Construct leaky bucket.
	 * @param rate_bytes_per_sec Exact leak rate in bytes per second.
	 * @param capacity_bytes Exact maximum whole-byte level.
	 */
	constexpr leaky_bucket(uint64_t rate_bytes_per_sec, uint64_t capacity_bytes) noexcept
		: rate_bytes_per_sec_(rate_bytes_per_sec)
		, capacity_bytes_(capacity_bytes)
		, level_numerator_(0)
		, last_ns_(0)
		, initialized_(false)
	{
	}

	/**
	 * @brief Check if packet should be allowed.
	 *
	 * @param now_ns Explicit monotonic timestamp in nanoseconds.
	 * @param bytes Whole-byte cost.
	 * @return true if added; false for overflow or timestamp regression.
	 */
	[[nodiscard]]
	KINETUM_ALWAYS_INLINE bool allow(uint64_t now_ns, std::size_t bytes) noexcept
	{
		if (KINETUM_UNLIKELY(!initialized_)) {
			last_ns_ = now_ns;
			initialized_ = true;
		} else if (KINETUM_UNLIKELY(now_ns < last_ns_)) {
			return false;
		} else if (now_ns > last_ns_) {
			const uint64_t elapsed_ns = now_ns - last_ns_;
			const detail::rate_numerator leaked =
				detail::accrued_numerator(elapsed_ns, rate_bytes_per_sec_);
			level_numerator_ = leaked >= level_numerator_ ? 0u : level_numerator_ - leaked;
			last_ns_ = now_ns;
		}

		static_assert(sizeof(std::size_t) <= sizeof(uint64_t));
		const detail::rate_numerator cost = detail::byte_numerator(static_cast<uint64_t>(bytes));
		const detail::rate_numerator capacity = detail::byte_numerator(capacity_bytes_);
		if (cost <= capacity && level_numerator_ <= capacity - cost) {
			level_numerator_ += cost;
			return true;
		}

		return false;  // Overflow
	}

	/** @return Whole occupied bytes, excluding retained fractional leakage. */
	[[nodiscard]] constexpr uint64_t level() const noexcept
	{
		return static_cast<uint64_t>(level_numerator_ / detail::RATE_DENOMINATOR);
	}

	/** @brief Empty the level and unbind its timestamp baseline. */
	void reset() noexcept
	{
		level_numerator_ = 0;
		last_ns_ = 0;
		initialized_ = false;
	}

    private:
	uint64_t rate_bytes_per_sec_;		  ///< Exact configured whole-byte leak rate.
	uint64_t capacity_bytes_;		  ///< Exact maximum whole-byte level.
	detail::rate_numerator level_numerator_;  ///< Exact level over the shared denominator.
	uint64_t last_ns_;			  ///< Last accepted timestamp.
	bool initialized_;			  ///< Whether the timestamp baseline is bound.
};

// =============================================================================
// Sliding Window Rate Limiter
// =============================================================================

/**
 * @brief Simple sliding window counter for request rate limiting.
 *
 * Counts events in a sliding time window. Useful for API rate
 * limiting where you want "N requests per M seconds".
 *
 * @par Thread Safety
 * One caller owns each window. Shared use requires external synchronization.
 */
class sliding_window {
    public:
	/**
	 * @brief Construct sliding window.
	 * @param max_count Maximum events allowed in one window; zero deliberately
	 *        denies every event.
	 * @param window_ns Positive window duration in nanoseconds.
	 * @throws std::invalid_argument when @p window_ns is zero.
	 */
	sliding_window(uint64_t max_count, uint64_t window_ns)
		: max_count_(max_count)
		, window_ns_(window_ns)
		, count_(0)
		, window_start_ns_(0)
		, initialized_(false)
	{
		if (window_ns_ == 0u) {
			throw std::invalid_argument("sliding_window: window duration must be positive");
		}
	}

	/**
	 * @brief Check if event should be allowed.
	 * @param now_ns Explicit monotonic timestamp in nanoseconds.
	 * @return true if counted; false at the configured limit or on timestamp
	 *         regression.
	 */
	[[nodiscard]]
	KINETUM_ALWAYS_INLINE bool allow(uint64_t now_ns) noexcept
	{
		if (KINETUM_UNLIKELY(!initialized_)) {
			window_start_ns_ = now_ns;
			initialized_ = true;
		} else if (KINETUM_UNLIKELY(now_ns < window_start_ns_)) {
			return false;
		} else if (now_ns - window_start_ns_ >= window_ns_) {
			window_start_ns_ = now_ns;
			count_ = 0;
		}

		if (count_ < max_count_) {
			++count_;
			return true;
		}

		return false;
	}

	/** @return Exact accepted event count in the current window. */
	[[nodiscard]] constexpr uint64_t count() const noexcept
	{
		return count_;
	}
	/** @return Saturated number of events still available in the current window. */
	[[nodiscard]] constexpr uint64_t remaining() const noexcept
	{
		return (count_ < max_count_) ? (max_count_ - count_) : 0;
	}

	/** @brief Clear event count and unbind the timestamp baseline. */
	void reset() noexcept
	{
		count_ = 0;
		window_start_ns_ = 0;
		initialized_ = false;
	}

    private:
	uint64_t max_count_;	    ///< Maximum accepted events in one window.
	uint64_t window_ns_;	    ///< Exact positive window duration in nanoseconds.
	uint64_t count_;	    ///< Accepted events in the current window.
	uint64_t window_start_ns_;  ///< First timestamp bound to the current window.
	bool initialized_;	    ///< Whether `window_start_ns_` carries a timestamp.
};

}  // namespace kinetum::algo
